### ISSUE TITLE
could not found Administrator button at all

### ISSUE THREAD

**Issue by benzAtNPS** [Devolutions/doc#1108]
### Contact Details

ben.zhang@nelnet.net

### Feedback

could not found Administrator button at all

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

I assume you mean the **_Administration_** button in Remote Desktop Manager, as shown in [Administration](https://docs.devolutions.net/rdm/windows/commands/administration/). You would need to be an administrator (have administrative rights) and in most cases use an [advanced data source](https://docs.devolutions.net/rdm/windows/data-sources/data-sources-types/advanced-data-sources/) in order to see the button and access its features.

If your are not an administrator, I would suggest contacting your IT administrator to talk with them about this situation. For any other issue, please contact our support technicians at [service@devolutions.net](mail to:service@devolutions.net). They have the knowledge and expertise to further assist you.

Best regards, 

The Devolutions Documentation Team
