### ISSUE TITLE
[Feedback]: On the delete web cache instructions it states to delete EO.WebBrowser.Cache.  It would be helpful to know the location of this file.  Is it in appdata or Program Files, etc?

### ISSUE THREAD

**Issue by fmagliaro** [Devolutions/doc#1109]
### Contact Details

fmaglia@uwindsor.ca

### Feedback

On the delete web cache instructions it states to delete EO.WebBrowser.Cache.  It would be helpful to know the location of this file.  Is it in appdata or Program Files, etc?
Franco Magliaro

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

After consulting our support team, the [Clear web browser cache](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/clear-web-browser-cache/) topic you mentioned needs to be updated.

To answer your question, if Remote Desktop Manager is in **_Program files_**, then the **_EO,WebBrowser.Cache_** folder should be located in the **_localappdata_**. In more recent versions of Remote Desktop Manager, the **_WebView2.Cache_** folder is now created instead of the **_EO,WebBrowser.Cache_** folder. They can both be found at the same location. So if you have both, you may delete (or rename) both. If you have only one of them, delete (or rename) only one of them.

However, if you have created an **_override.cfg_** file in the application folder, as explained in [Configuration file location](https://docs.devolutions.net/rdm/windows/installation/client/configuration-file-location/#override-the-default-path), the cache folders may be saved elsewhere.

I hope this answers your question. For more information about this, I suggest you contact our support technicians at [service@devolutions.net](mailto:service@devolutions.net). They have the knowledge and expertise to further assist you. In the meantime, we will update our topic to reflect what we just discussed. Thank you for bringing this to our attention!

Best regards, 

The Devolutions Documentation Team

**Comment by JeanSebastienSimard** [comment]
Hello again, 

We have updated the [Clear web browser cache](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/clear-web-browser-cache/) topic following your feedback. Thank you again for your contribution!

Best regards, 

The Devolutions Documentation Team
