### ISSUE TITLE
[Feedback]: Problems with RDP to Azure AD joined target from Windows 11 client

### ISSUE THREAD

**Issue by dcdorsey777** [Devolutions/doc#1362]
### Contact Details

ddorsey@pcfd.org

### Feedback

Since upgrading my workstation to Windows 11 from Windows 10, I have been unable to RDP to target PC's that are AzureAD joined.  On the "General" tab of the Edit RDP pane, I have the following:
Username: AzureAD\user@mydomain.TLD  (I have generisized my domain here)
Domain: <blank>
Password: <remembered>
These all worked under Windows 10.  Now, when I try to connect, I get a message that "Your credentials did not work", and showing the user name as "user@mydomain.TLD".  

I have tried adding a "." in two different places: 1) as .\AzureAD\user@mydomain.TLD, and in the "Domain" field.  Neither resolves the problem.  (And the instructions are ambiguous - which place do you mean to add the "."?

I understand this is NOT a place for support.  Just adding my feedback.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [RDP username automatically changed if the client is Azure AD joined on Windows 11](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/rdp-username-changes-to-azure-ad-user/)
* Content Source: [/content/en/kb/remote-desktop-manager/troubleshooting-articles/rdp-username-changes-to-azure-ad-user.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/troubleshooting-articles/rdp-username-changes-to-azure-ad-user.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your feedback.

The instructions are taking place in the properties of your RDP entry. To access these properties, right-click the RDP entry and choose **_Properties_**. Upon doing so, the initial screen presented will include the **_Username_** and **_Domain_** fields, which are talked about in the knowledge base topic.

The problem when switching to Windows 11 is that if the **_Username_** (the field above the _**Domain**_ field) does not contain the characters "\" and/or "@" **and** the _**Domain**_ field is empty, the content of the **_Username_** field gets replaced by "AzureAD\user" when joining Azure AD, regardless of what the target system is. Writing a period (".") inside the **_Domain_** field instead of leaving it empty prevents the content of the **_Username_** field from getting replaced.

If that did not fix the issue, please let us know and we will forward this thread to our support technicians who have the knowledge and expertise to further assist you. In the meantime, we will look into clarifying our documentation regarding this issue.

Best regards, 

The Devolutions Documentation Team

**Comment by dcdorsey777** [comment]
Please give me a little while to respond before you close!
As stated, my Username field DOES contain BOTH a "\" AND an "@".  Also as stated, I have tried with and without a "." in the domain field.  There must be something else in your answer that I am too stupid to understand.  And it's probably risky, but I'm posting a screen shot of my settings WITH my user name to make sure I'm not leaving anything out, as well as the response when I try to connect to an AzureAD (aka Entra ID) joined Windows machine.  I have ensured that AzureAD\adm_pcfd@pcfd.org is a member of the remote desktop users group.  I have DISabled "require NLA, per instructions  Again, I don't expect any support here, but wanted to clarify my observation.

**Comment by JeanSebastienSimard** [comment]
Hello, 

Sorry for closing this thread too soon, I knew that you would still be able to write back.

I don't have the expertise to further assist you unfortunately. We have forwarded your issue to our support technicians; they will be opening a case for you. You can expect a response from them within 48 business hours. They will update us about your case and, if applicable, will give us information to add to our documentation.

We have nonetheless updated our documentation to try clarifying it: [RDP username of Azure AD client automatically changes on Windows 11](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/rdp-username-changes-to-azure-ad-user/). Thank you again for your feedback!

I will be closing this thread now, but don't worry, our support team will get the entirety of the information you forwarded us here. I'm sure they will find it useful.

Best regards,

The Devolutions Documentation Team
