### ISSUE TITLE
[Feedback]: Link to download tools from Fortinet

### ISSUE THREAD

**Issue by bitan-benny** [Devolutions/doc#1555]
### Contact Details

bitan@bsmart.co.il

### Feedback

Link to download tools from Fortinet
Hello, the link leads to the welcome page,
Is there an option to connect with Forti SSL VPN or does this option no longer exist and you have to connect manually before opening the connection?
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Forticlient](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/forticlient/)
* Content Source: [/content/en/kb/remote-desktop-manager/troubleshooting-articles/forticlient/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/troubleshooting-articles/forticlient/index.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

The link leads to the Fortinet support login page since a paying account is needed to download the tools.

Regarding the option to connect with to SSL VPN, we have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

We will be closing this issue now.

Best regards, 

The Devolutions Documentation Team
