### ISSUE TITLE
[Feedback]: Request for more details of "Unsafe Google Chrome integration"

### ISSUE THREAD

**Issue by Danvo1** [Devolutions/doc#1955]
### Contact Details

This github issue

### Feedback

Hi,
we updated our RDM to the latest version and now we see a warning which leads to this article: [https://docs.devolutions.net/rdm/kb/rdm-windows/knowledge-base/unsafe-google-chrome-integration/](https://docs.devolutions.net/rdm/kb/rdm-windows/knowledge-base/unsafe-google-chrome-integration/)

I'd like to understand how chromium is integrated into RDM and why this leads to an outdated version of the integrated browser.

Also I'd like to know what are your steps to solve or mitigate this issue and when we can expect a response.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Unsafe Google Chrome integration in Remote Desktop Manager Windows](https://docs.devolutions.net/rdm/kb/rdm-windows/knowledge-base/unsafe-google-chrome-integration/)
* Content Source: [/content/en/rdm/kb/rdm-windows/knowledge-base/unsafe-google-chrome-integration.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/kb/rdm-windows/knowledge-base/unsafe-google-chrome-integration.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your questions to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

To share thoughts on specific product features or for any questions regarding our products, please email our support team at [service@devolutions.net](mailto:service@devolutions.net). Your input is invaluable to us.

Best regards, 

The Devolutions Documentation Team

**Comment by Danvo1** [comment]
Hello,

what is the reason you don't want to discuss this publicly?

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your reply. Our technical writing department unfortunately does not have the expertise to address your specific technical question, but our technical support team can help. That's why we recommended you contact them. We would not have any issue discussing this matter here if we had the information.

Typically, we would have initiated a support case on your behalf using your contact details. However, as we do not have your contact information, we were unable to do so. If you provide us with an email address, we can promptly open a support case for you. Alternatively, you can reach out to our support team directly at [service@devolutions.net](mailto:service@devolutions.net). Whichever option you choose, a technician from our support team will respond within 48 business hours.

We appreciate your understanding and cooperation.

Best regards,

The Devolutions Documentation Team

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your reply. Our technical writing department unfortunately does not have the expertise to address your specific technical question, but our technical support team can help. That's why we recommended you contact them. We would not have any issue discussing this matter here if we had the information.

Typically, we would have initiated a support case on your behalf using your contact details without any further action required from you. However, as we do not have your contact information, we were unable to do so. If you provide us with an email address, we can promptly open a support case for you. Alternatively, you can reach out to our support team directly at [service@devolutions.net](mailto:service@devolutions.net). Whichever option you choose, a technician from our support team will respond within 48 business hours.

We appreciate your understanding and cooperation.

Best regards,

The Devolutions Documentation Team
