### ISSUE TITLE
How to get CyberArk Dashboard?

### ISSUE THREAD

**Issue by 51sec** [Devolutions/doc#959]
[Enter feedback here]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [CyberArk Dashboard configuration and use](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/cyberark-dashboard-configuration/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/cyberark-dashboard-configuration.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/cyberark-dashboard-configuration.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your feedback! I would need more information in order to correctly guide you. Here are some possible solutions:

- The **_Configuration_** section of the [CyberArk Dashboard configuration and use](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/cyberark-dashboard-configuration/#configuration) topic explains how to create a CyberArk Dashboard entry in Remote Desktop Manager.
- 
- To learn how to create an entry in Remote Desktop Manager from the start, see [Create an entry](https://docs.devolutions.net/rdm/windows/commands/edit/entries/creating-new-entry/).

- If you need information about CyberArk, I suggest taking a look at their [CyberArk Docs](https://docs.cyberark.com/Portal/Content/Resources/_TopNav/cc_Portal.htm) or [contacting them](https://www.cyberark.com/contact/) directly.

For any other thoughts on specific product features or if you have any more questions, please email our support team at [service@devolutions.net](mailto:service@devolutions.net). Your input is invaluable to us.

Best regards,

Devolutions Documentation team
